'''
Each new term in the Fibonacci
sequence is generated by adding
the previous two terms.
By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55,
89, ...

By considering the terms in the
Fibonacci sequence whose values
do not exceed four million, find
the sum of the even-valued terms.
'''

def fibEvenSum(l_last,last,fibSum):
    #end when last >= 10**6
    if last>=4*(10**6):
        return fibSum
    if last%2==0:
        fibSum+=last
    return fibEvenSum(last,last+l_last,fibSum)
    #calc next

print(fibEvenSum(2,3,2))#4613732

a=2
b=3
fibS = 2

while b < 4*(10**6):
    if b%2==0:
        fibS+=b
    b=a+b
    a=b-a
print(fibS)#4613732
